// <auto-generated />
using BillingApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillingApi.Migrations
{
    [DbContext(typeof(BillAppDbContext))]
    [Migration("20210125175906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BillingApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Discount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 10,
                            Manufacturer = "USA",
                            Name = "T-Shirt",
                            Price = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Discount = 5,
                            Manufacturer = "CA",
                            Name = "Pants",
                            Price = 150.0
                        },
                        new
                        {
                            Id = 3,
                            Discount = 0,
                            Manufacturer = "China",
                            Name = "Hat",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 4,
                            Discount = 10,
                            Manufacturer = "UK",
                            Name = "Shoes",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 5,
                            Discount = 15,
                            Manufacturer = "USA",
                            Name = "Suit",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 6,
                            Discount = 10,
                            Manufacturer = "USA",
                            Name = "Jacket",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 7,
                            Discount = 15,
                            Manufacturer = "USA",
                            Name = "Dress",
                            Price = 500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
